import BrandLink from "../components/Brandlink/Brandlink"
import FactNumber from "../components/FactNumber/FactNumber"

const About = () => {
  return (<>
    <div className="flex items-center">
      <div className=" relative my-20 mx-auto">
        <div className=" absolute -z-1  bg-orange-300 h-14 rounded-full top-0 w-14 "></div>
        <BrandLink className={"text-6xl ml-4"} />
      </div>
    </div>

    <div className="py-10 text-justify">
      <div className="mx-auto w-2/3">
        <p className="mb-4">
          Glamify is the leading premium beauty platform in Asia. Offering more than 130,000 beauty and
          lifestyle products in online shops, the beauty marketplace and more than 2,000 stores, Glamify
          inspires customers to live their own kind of beauty by a previously unparalleled assortment.
        </p>
        <div>
          <p>
            The continued expansion of the fast-growing e-commerce business is the focus of the
            <span className="font-krona">#forwardbeauty</span> , DigitalFirst strategy programme. In fiscal
            year 2019/2020, Glamify generated sales of 3.2 billion euros in the areas of perfumery, decorative
            cosmetics, skin and hair care as well as nutritional supplements and accessories. <span className="font-krona"> #letsdobeautiful</span>

          </p>
        </div>
      </div>

    </div>
    <div className="bg-orange-300">
      <div className="flex flex-col md:flex-row py-10 space-y-10 md:space-y-0 md:w-3/4 mx-auto ">
        <FactNumber
          icon={'people'}
          number={'20000'}
          title={'Beauty Experts'}
          description={'Strive to make their customers  more beautiful and thus happier'} />

        <FactNumber
          icon={'revenue'}
          number="3.2"
          title="Billion Euros"
          description="revenue was generated by Glamify in the 2022/23 financial year"
        />
        <FactNumber
          icon={'shop'}
          number="130,000"
          title="Care Products"
          description="because we care about you in online shops, and in stores"
        />
      </div>
    </div>


    <div className="text-center w-2/3 mx-auto my-20">
      <h4 className="font-krona mb-4">Imprint</h4>
      <p>Glamify Inc. New-Baneshwor Kathmandu</p>
      <p>
        You can reach us by email at: servicewelly@gmail. Our deliveries go out every Sunday evening so
        you can get them as early in the week as possible
      </p>
    </div>

  </>)
}
export default About